name: truthliesdetector
description: "A new Flutter project."
publish_to: 'none' # 只在本地跑，不會發佈到 pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_overlay_window: ^0.5.0

  # iOS風格icons
  cupertino_icons: ^1.0.8

  # 檔案選擇 (支援 Web, Android, iOS, Desktop)
  file_picker: ^10.3.2  

  # Http 請求
  http: ^1.2.1

  # 截圖 (支援 Flutter 3.x)
  screenshot: ^3.0.0

  # 資料庫連線 (PostgreSQL)
  postgres: ^2.4.6

  # 本地儲存 (用戶登入狀態)
  shared_preferences: ^2.2.2

  # 狀態管理
  provider: ^6.1.1

  intl: ^0.19.0

  # 密碼加密
  crypto: ^3.0.3

  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/logo1.png
    - lib/assets/logo2.png